name: Build & Test

on:
  push:
    branches: [ "master" ]
    tags: ['*']
  pull_request:
    types: [ opened, synchronize ]
    branches: [ "master" ]

env:
  NuGetDirectory: ${{ github.workspace }}\nuget

jobs:
  build_test_and_pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            8.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore
      - name: Tests
        run: dotnet test -c Release --no-build --verbosity normal